"""empty message

Revision ID: 468aedb39aec
Revises: f12dd4cd6d45
Create Date: 2024-06-21 18:32:37.463780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '468aedb39aec'
down_revision = 'f12dd4cd6d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('surname', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('post_office', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('additional', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('additional')
        batch_op.drop_column('post_office')
        batch_op.drop_column('city')
        batch_op.drop_column('email')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('surname')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
