"""empty message

Revision ID: 825f85fd8669
Revises: db7feb5be435
Create Date: 2024-05-07 22:41:00.927061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825f85fd8669'
down_revision = 'db7feb5be435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Text(), nullable=False),
    sa.Column('in_stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
